### ISSUE TITLE
Failed to mount component: template or render function not defined.

### ISSUE THREAD

**Issue by astroanu** [chryb/vue-c3#11]
I keep getting this on the latest version. There is also a stackoverflow question related to the same problem. https://stackoverflow.com/questions/50440919/failed-to-mount-component-using-vue-c3

Is there a fix for this ?

**Comment by chryb** [comment]
I will look into this within the next two days because I'm currently a bit busy.

**Comment by astroanu** [comment]
For now reverting to `v.1.1.1` works fine. But i want to update the package to the latest.

**Comment by chryb** [comment]
It should be working now with the latest version (1.2.8).

**Comment by astroanu** [comment]
Cool. i'll take a look :)

**Comment by chryb** [comment]
If the project persists feel free to reopen the issue
