### ISSUE TITLE
IE 11 Compatibility

### ISSUE THREAD

**Issue by dlip** [chryb/vue-c3#12]
When I'm using your component I get an error:

script1003: expected ':'

**Comment by gihalu** [comment]
I am having the same problem. I changed my import statement to "vue-c3/src" but still have the same problem. I am thinking this is because of the following configuration, but have not been able to figure out how to adjust this successfully:

`module: {
    rules: [
      { 
          test: /\.ts$/, 
          loader: "ts-loader",
          exclude: /node_modules/,
          options: {
              appendTsSuffixTo: [/\.vue$/]
          }
      },
      {
        test: /\.vue$/,
        loader: 'vue-loader',
        options: vueLoaderConfig
      },
      {
        test: /\.js$/,
        loader: 'babel-loader',
        include: [resolve('src'), resolve('test')]
      }
    ]
  }`

**Comment by artemanufrij** [comment]
Tested on a lot of systems. Now it works as expected.

Issue can be closed.
