### ISSUE TITLE
css, axis issues  

### ISSUE THREAD

**Issue by greenpdx** [chryb/vue-c3#6]
[SelDetail.zip](https://github.com/chryb/vue-c3/files/1561691/SelDetail.zip)
I am use vue-c3 to create a chart and I have two problems.
First: I do not want to display the axis values.  I have tried 
```
axis: {
  x: {
    show: false
  }
  y:  {
     show: false
   }
}
```
but this hides the axis values and the axis, I just want to hide the values.

Next, I am using a line chart but the area under the line is black. I found a c3 problem that states that c3.css is not being used.  Does vue-c3 include c3.css? if not how do I add it to chart?
I have attached the file zipped. I am hacking it now, so it looks funky

**Comment by chryb** [comment]
Hi, I will look into it.

**Comment by greenpdx** [comment]
When I imported c3.css i worked
```
<script>
import Vue from 'vue'
import VueC3 from 'vue-c3'
import '../assets/c3.min.css'
import d3 from 'd3'

export default {
```

I am still trying to remove the axis tick labels. I can remover the axis label but not the tick.

**Comment by chryb** [comment]
vue-c3 is just a wrapper around c3. You should try this: [https://stackoverflow.com/questions/27294144/c3js-how-to-hide-ticks-on-y-axis-y-axis-label-is-cut-off](https://stackoverflow.com/questions/27294144/c3js-how-to-hide-ticks-on-y-axis-y-axis-label-is-cut-off)

**Comment by chryb** [comment]
Reopen the issue if that didn't fix your problem
