### ISSUE TITLE
Needed help with setting up vue-c3

### ISSUE THREAD

**Issue by checkthestatistics** [chryb/vue-c3#7]
First of all, I have problems with creating handler property in main component, due to the fact that example shows that we need to create this property with **new Vue()** value:  `handler: new Vue()` and Vue returns error: Vue is not defined.

Secondly i dont understand why example shows event like:       `this.handler.$emit('init', options)`. Shouldnt be it something like `this.$emit('init', options)`, cause the example ones returns an error?

Could someone explain how to properly use this vue-c3 package?

Here is my code:

**Main component:**

```
    <template>
    <div>
      <vue-chart @myEvent="init" :handler="handler"></vue-chart>    
    </div>
    </template>
    
    <script>
    import VueChart from '@/components/VueChart'
    
    export default {
      name: 'HelloWorld',
      data () {
        return {
          handler: {}
        }
      },
      components: { VueChart }
    }
    </script>
```

**Chart component:**

```
    <template>
    	<div>
    		Content
    	</div>
    </template>
    
    <script>
    export default {
    	name: 'VueChart',
    	props: ['handler'],
    	mounted () {
    		const options = {
    			data: {
    				columns: [
    					['data1', 2, 4, 5],
    					['data2', 1, 8, 9]
    				]
    			}
    		}
    		this.$emit('init', options)
    	}
    }
    
    </script>
```

**Comment by chryb** [comment]
No, you forgot to import Vue beforehand. 
`
<script>
import Vue from 'vue'
...

export default {
  ...
  data() {
    return {
      handler: new Vue()
    }
  }
}
</script>`

I hope that helps.
