### ISSUE TITLE
Error: Couldn't find preset "latest" relative to directory

### ISSUE THREAD

**Issue by vollyimnetz** [chryb/vue-c3#8]
Hi,
i use webpack 4 with babel and the following setting:
```
{
    "presets": [
        [
            "env",
            {
                "modules": false,
                "targets": {
                    "browsers": [
                        "> 1%",
                        "last 2 versions",
                        "not ie <= 10"
                    ]
                }
            }
        ]
    ],
    "plugins": [
        "transform-object-rest-spread"
    ]
}
```

As soon i try to import "vue-c3" or "node_modules/vue-c3/dist/index.js" i get the error
"Couldn't find preset "latest" relative to directory [... the directory of vue-c3 ...]".
**How can i fix that? Should this be fixed in your project?**

**Comment by vollyimnetz** [comment]
Ah, ok after installing babel-preset-latest it worked.
`npm install --save-dev babel-preset-latest`

But as i learned babel-preset-latest is deprecated (use preset-env)
https://babeljs.io/docs/plugins/preset-latest/

**Comment by chryb** [comment]
I've updated all dependencies of the project including the babel preset env. I hope that helped.
