### ISSUE TITLE
package broken?

### ISSUE THREAD

**Issue by akashgoswami** [chryb/vue-c3#9]
Hi Chrys,

I just updated the latest package and it's not being picked up by webpack. 

ERROR in ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/components/LineChartC3.vue
Module not found: Error: Can't resolve 'vue-c3' in '/home/ec2-user/environment/yacp/app/src/components'
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/components/LineChartC3.vue 5:0-27
 @ ./src/components/LineChartC3.vue
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/views/Dashboard.vue
 @ ./src/views/Dashboard.vue
 @ ./src/router/index.js
 @ ./src/main.js

It seems like the **main** in package.json still points to dist/index.js while index.js is no longer available in the latest release. I temporarily changed the main to src/index.js and it works correctly.

**Comment by wald-tq** [comment]
using version 1.2.4 I had to change it to:

      "main": "dist/vue-c3.min.js",

**Comment by wald-tq** [comment]
See Pullrequest #10

**Comment by chryb** [comment]
I already updated it yesterday. Sorry for not replying you. Currently, I'm a bit busy.
Does it work now?

**Comment by wald-tq** [comment]
if you merge my pull-request  #10 it should be working

**Comment by reginaldojunior** [comment]
Not works i need version 1.1.1 to works for me

**Comment by chryb** [comment]
#10 Merged

**Comment by chryb** [comment]
1.2.5 should work now

**Comment by billcheng** [comment]
1.2.5 is giving me this

Failed to mount component: template or render function not defined.
found in
---> <VueC3>

but reverting back to 1.1.1 works fine

**Comment by chryb** [comment]
I switched from webpack 4 to rollup and now it should be working in v1.2.8.
